# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(help_text='郵便番号', max_length=7)),
                ('pref', models.CharField(max_length=50, verbose_name='郵便番号')),
                ('city', models.CharField(max_length=100, verbose_name='郵便番号')),
                ('town', models.CharField(max_length=255)),
                ('kana_pref', models.CharField(max_length=50)),
                ('kana_city', models.CharField(max_length=100)),
                ('kana_town', models.CharField(max_length=100)),
            ],
        ),
    ]
