# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170525_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='kana_pref',
            field=models.CharField(help_text='都道府県名カナ', max_length=51, null=True, verbose_name='都道府県名カナ'),
        ),
    ]
